name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Tag Format
        id: verify_tag
        run: |
          if [[ ! ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Expected vX.X.X where X are numbers."
            exit 1
          fi
      
      - name: Build the Docker image
        if: success()
        run: docker build . --file Dockerfile --tag speedtest:${{ github.ref_name }}
